<?php

namespace APP\EmpresaBundle\Repository;

/**
 * EmpresarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresarRepository extends \Doctrine\ORM\EntityRepository
{
}
