<?php

namespace APP\EmpresaBundle\Repository;

/**
 * ParcelasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcelasRepository extends \Doctrine\ORM\EntityRepository
{
}
