<?php

namespace APP\EmpresaBundle\Repository;

/**
 * ReceitaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceitaRepository extends \Doctrine\ORM\EntityRepository
{
}
