empresa_empresar:
    resource: "@EmpresaBundle/Resources/config/routing/empresar.yml"
    prefix:   /empresar

empresa_produtos:
    resource: "@EmpresaBundle/Resources/config/routing/produtos.yml"
    prefix:   /produtos


empresa_categoria:
    resource: "@EmpresaBundle/Resources/config/routing/categoria.yml"
    prefix:   /categoria

empresa_fotos:
        resource: "@EmpresaBundle/Resources/config/routing/fotos.yml"
        prefix:   /fotos

empresa_receita:
        resource: "@EmpresaBundle/Resources/config/routing/receita.yml"
        prefix:   /receita
        
empresa_clientes:
        resource: "@EmpresaBundle/Resources/config/routing/clientes.yml"
        prefix:   /clientes
        
empresa_parcelas:
        resource: "@EmpresaBundle/Resources/config/routing/parcelas.yml"
        prefix:   /parcelas        
        
        
        