empresa:
    resource: "@EmpresaBundle/Resources/config/routing.yml"
    prefix:   /

usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /


    
UsuarioBundle:
    resource: "@UsuarioBundle/Controller/"
    prefix: /usuario
    type:   annotation
