# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        APP\UsuarioBundle\Entity\Usuario: sha512
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        banco_de_dados:
             entity: {class: UsuarioBundle:Usuario }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        secured_area:
            pattern: ^/
            form_login:
                success_handler: authentication.handler.login_success_handler
                check_path: /usuario/login
                login_path: /usuario/login
                
            logout:
                path: /logout
                target: /catalogo
        
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            
            
    access_control:
        - { path: ^/teste, roles: ROLE_USER}