APP\EmpresaBundle\Entity\Fotos:
    type: entity
    table: null
    repositoryClass: APP\EmpresaBundle\Repository\FotosRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        arquivo:
            type: string
            length: 255
            nullable: true
        principal:
            type: boolean
    lifecycleCallbacks: {  }
