<?php

namespace APP\UsuarioBundle\Repository;

/**
 * TelefoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;

 

class TelefoneRepository extends EntityRepository 
{
    
    
}
