<?php

namespace APP\UsuarioBundle\Repository;

/**
 * TelefoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelefoneRepository extends \Doctrine\ORM\EntityRepository
{
}
