receita_index:
    path:     /
    defaults: { _controller: "EmpresaBundle:Receita:index" }
    methods:  GET

receita_show:
    path:     /{id}/show
    defaults: { _controller: "EmpresaBundle:Receita:show" }
    methods:  GET

receita_new:
    path:     /new
    defaults: { _controller: "EmpresaBundle:Receita:new" }
    methods:  [GET, POST]

receita_edit:
    path:     /{id}/edit
    defaults: { _controller: "EmpresaBundle:Receita:edit" }
    methods:  [GET, POST]

receita_delete:
    path:     /{id}/delete
    defaults: { _controller: "EmpresaBundle:Receita:delete" }
    methods:  DELETE
